Repository kartikeysingh6/kartik_python, pull requests merged in 2021-10, with the labels that each got.

#2 Added File Transfer Code
  FileTransfer/Client.py
  FileTransfer/server.py
Labels: good first issue, hacktoberfest-accepted

#3 added program for kth smallest integer
  kthSmallest.java
Labels: hacktoberfest-accepted

#4 Added FeatureDetection Python file
  FeatureDetect.py
Labels: good first issue, hacktoberfest-accepted

#5 added java program for bubble sort
  BubbleSort.java
Labels: hacktoberfest-accepted

#7 added heap sort for c++
  Heap Sort.cpp
Labels: hacktoberfest-accepted

#6 Create strong_pass_gen
  strong_pass_gen.py
Labels: hacktoberfest-accepted

#10 Added another cringe image
  CringeJokes/imgs/8.jpg
Labels: enhancement, good first issue, hacktoberfest-accepted

#11 Create RadixSort.py
  RadixSort.py
Labels: enhancement, hacktoberfest-accepted

#12 Added the worst sorting algorithm the BogoSort
  BogoSort.py
Labels: enhancement, hacktoberfest-accepted

#9 Added fizzbuzz.py
  fizzbuzz.py
Labels: good first issue, hacktoberfest-accepted

#13 Create CountSort.py
  CountSort.py
Labels: enhancement, hacktoberfest-accepted

#15 Created photo swap.ipynb
  photo swap.ipynb
Labels: hacktoberfest-accepted

#16 Create binarysearch.py
  binarysearch.py
Labels: good first issue, hacktoberfest-accepted

#17 merge-sort code for cpp added
  Merge_Sort.cpp
Labels: enhancement, hacktoberfest-accepted

#18 Create a mandelbrot set
  madelbrot.py
Labels: good first issue, hacktoberfest-accepted

#20 added code for sorting an array of 0 and 1
  sort0and1.java
Labels: hacktoberfest-accepted

#25 ToDo APP Dart Code.
  to_do_app.dart
Labels: good first issue, hacktoberfest-accepted

#26 Create FlipkartSpammerBot
  Spammer/FlipkartSpammerBot
Labels: enhancement, good first issue, hacktoberfest-accepted

#22 Face Detection using Python
  Face Detection/face_detect_cam.py
  Face Detection/haar_face.xml
  Face Detection/readme.md
Labels: hacktoberfest-accepted

#44 create pong_game.py
  Pong_game.py
Labels: hacktoberfest-accepted
