Repository kartikeysingh6/kartik_python, pull requests merged in 2022-10, with the labels that each got.

#48 Add files via upload
  recursion.cpp
  sum_of_all_elements_of_an_array.cpp
Labels: hacktoberfest

#49 primitive class type conversion
  OOPS/TypeConversionPrimitiveNClass.cpp
Labels: hacktoberfest

#51 This file has the solution of tower of hanoi problem in java
  heirarchical.java
  towerOfHanoi.java
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#53 CodeForces setup
  codeforce.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#54 type conversion part 1
  OOPS/TypeConversionClassNClass1.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#55 multilevel inheritance in java
  multilevel.java
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#56 type conversion part 2 (final)
  OOPS/TypeConversionClassNClass2.cpp
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#57 encapsulation in java
  abstraction.java
  encapsulation.java
Labels: hacktoberfest-accepted, hacktoberfest

#59 contains switch case use in java
  switchcase.java
Labels: hacktoberfest-accepted, hacktoberfest

#58 templates in cpp
  Template.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#60 implements data hiding in java
  dataHiding.java
  threading.java
Labels: hacktoberfest-accepted, hacktoberfest

#61 added flappybird project for hacktoberfest
  Flappybird/README.md
  Flappybird/Screenshots/Screenshot (144).png
  Flappybird/Screenshots/Screenshot (146).png
  Flappybird/Screenshots/Screenshot (147).png
  Flappybird/Screenshots/Screenshot (149).png
  Flappybird/cloud1.png
  Flappybird/flappybird.py
  Flappybird/flappybird2.png
  Flappybird/sfx_hit.wav
  Flappybird/sfx_point.wav
  Flappybird/sfx_wing.wav
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#62 Insertion sort in CPP
  Insertion.cpp
  Quick.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#52 Tic Tac Toe game
  tic_tac_toe.py
Labels: hacktoberfest-accepted

#64 Commited Database Creation technique
  Database in Python/createDatabase.py
  Database in Python/demoMysqltest.py
Labels: hacktoberfest-accepted
