Repository kartikeysingh6/kartik_python, pull requests merged in 2023-10, with the labels that each got.

#67 Create CoolPythonCode.py
  CoolPythonCode.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#68 Added a scientific calculator.py
  scientific_calculator.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#69 Snake Game Implementation using Pygame
  SnakeGame.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#70 Added Jain Malik
  CringeJokes/imgs/Screenshot_20201015-000114.jpg
  Sorting Visualizer/sortingAlgos.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#71 Update GUIWeatherApp.py
  GUIWeatherApp.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest

#72 fix/added null check to city
  CoWinAlertPincode.py
Labels: hacktoberfest-accepted, hacktoberfest

#74 Add LICENSE
  LICENSE
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest

#75 Create chatbot.py
  chatbot.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#76 Adding Bitcoin Tracker
  BitcoinTracker.py
  CreditCardFraudDetection.ipynb
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#77 Added a new Message Spam Project
  Message-Spam/README.md
  Message-Spam/mesaage_spam.py
  Message-Spam/requirements.txt
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
